### ISSUE TITLE
Allow json files from file:// protocol

### ISSUE THREAD

**Issue by adamplumb** [ifl0w/RandomWallpaperGnome3#68] opened 2019-07-12 23:43 UTC
I wanted to be able to set up my own custom json file on my local machine, and point to that without requiring a web server.  So I put in a URL like so: `file:///home/aplumb/path/to/file.json`.  Unfortunately this didn't work, so I ended up uploading the json file to a public web space and that got it working.  But it would be nice to allow this for local files as well.

**Comment by ifl0w** [comment] 2019-07-13 14:14
Hello, the generic JSON source uses libsoup to request the JSON data and therefore only accepts URLs that work with an HTTP GET request. 

I interpret this issue as a duplicate of #30 and therefore will close it. 
Thank you for your support!

**Closed by ifl0w** 2019-07-13 14:14 UTC
