### ISSUE TITLE
Please update to gnome 3.34

### ISSUE THREAD

**Issue by tnilzon** [ifl0w/RandomWallpaperGnome3#79] opened 2020-01-04 16:08 UTC
There are several issues with this extension in gnome 3.34 (some already listed on this page). Please update, it's a great extension!
/Thanks

**Comment by AlexWayfer** [comment] 2020-01-09 09:05
Duplicate of #72.

**Comment by ifl0w** [comment] 2020-04-15 18:51
#72 is merged. Closing this issue.

**Closed by ifl0w** 2020-04-15 18:51 UTC
