### ISSUE TITLE
Crashes GNOME 3.30.1 on ArchLinux

### ISSUE THREAD

**Issue by luca-viggiani** [ifl0w/RandomWallpaperGnome3#45] opened 2018-10-19 08:23 UTC
Hi it happens quite frequently that the very first time I click on "New Wallpaper", the icons blink for a while then GNOME Shell crashes and the takes me back to the login screen. After logging in, the new wallpaper is actually there and successfully applied to the desktop.
Also, after that crash, I can fetch new wallpapers without any crashes.

**Comment by AlexWayfer** [comment] 2018-10-19 08:35
For me it looks like windows borders disappearing and then shell reloading, without login screen.

But it doesn't occur every time.

**Comment by ifl0w** [comment] 2018-10-19 12:58
I guess that you are on Wayland and this issue is related to #19.
Sadly this seems to be a bug in the gnome-shell with setting a wallpaper through gjs. So there is probably nothing I can do right now in the extension to fix this problem. 
However, I did not face this problem in gnome versions greater 3.26 and I know that it does not occur on all arch installations. (at least for me)

The best workaround I can provide right now is to switch back to the Xorg server instead of Wayland. On Xorg, this "crash" is not as dramatic since the window manager simply restarts (not possible in wayland). You will probably only end up with a broken extension panel (actually only the history list will be broken) until the next window manager restart. You can manually restart the window manager under Xorg by opening the command window with `alt + f2` and executing the command `r`.

I'll be able to further investigate the bug if I encounter a way to reliably reproduce the issue. Any help is appreciated and welcomed!
I am sorry for the inconvenience.

**Comment by AlexWayfer** [comment] 2018-10-19 13:15
> I guess that you are on Wayland and this issue is related to #19.

I guess I'm on Xorg, but I'm not sure how to check.

> On Xorg, this "crash" is not as dramatic since the window manager simply restarts (not possible in wayland). 

Oh, yeah, this is my case.

**Comment by luca-viggiani** [comment] 2018-10-19 13:16
Yes, I'm on Wayland (sorry I forgot to mention this important information).
Yes it was working fine at least until 3.28 also on Wayland.
Maybe it's something related to Intel viedo card? I've a Intel® HD Graphics 620 (Kaby Lake GT2) card.
Thanks!

**Comment by luca-viggiani** [comment] 2018-10-19 13:18
> > I guess that you are on Wayland and this issue is related to #19.
> 
> I guess I'm on Xorg, but I'm not sure how to check.
> 
> > On Xorg, this "crash" is not as dramatic since the window manager simply restarts (not possible in wayland).
> 
> Oh, yeah, this is my case.

Try to run this on a terminal
`echo $XDG_SESSION_TYPE`
It should output "wayland" or "X11"

**Comment by ifl0w** [comment] 2018-10-19 13:32
@AlexWayfer Additionally to luca-viggiani's test, you can also try to restart the window manager as described in my former post. This is only possible on Xorg.

@luca-viggiani Sadly I really could not determine a common denominator between problem instances. So I do not think that it is a problem with some particular hardware. But I figured that the underlying problem can occur on any setup. 
I personally think that it is some invalid memory access in GJS due to some garbage collection feature. But that is only a guess since I am not really familiar with the gnome-shell code base.

Also, the problem disappeared sometimes when I reinstalled my OS but that, of course, is not a viable fix.

**Comment by luca-viggiani** [comment] 2018-10-23 13:53
Hi, today I got an update on gjs package on Arch and since then I did not experience any further crash. I'll keep an eye on it and give a feedback a few days to see if the issue is actually gone.

**Comment by ifl0w** [comment] 2018-10-23 14:12
Thanks for the update.

**Comment by luca-viggiani** [comment] 2018-10-30 09:36
Hi, unfortunately it just happened again... :(
I noticed that sometimes when I click on the icon and the menu appear, the history is empty. In that case, if I click on "New Wallpaper", the shell crashes but after that the history shown correctly.

**Comment by luca-viggiani** [comment] 2018-10-31 14:13
I do confirm that if the menu doesn't show the history and a new wallpaper is requested, gnome shell crashes. If I restart the extension (or the entire shell) and the history menu is then visible, I can safely request a new wallpaper. It seems that in certain cases the extension is not able to load the history and after new wallpaper is set, it crashes. Perhaps when it tries to update the history?

**Comment by ifl0w** [comment] 2018-11-01 20:08
The history elements are cached for a better performance in long lists. Otherwise, the menu would be opening really slow if the history is greater than 50 elements. This cache might break when the shell crashes and it will only be regenerated when the shell is restarted.

Luckily I just pushed some commits that also enhance the stability of the cache.
So the history list might be fixed now but the crashes most certainly will still occur.

**Comment by ifl0w** [comment] 2020-04-15 19:32
Closing due to inactivity and I do not longer support this gnome version.

**Closed by ifl0w** 2020-04-15 19:32 UTC
