### ISSUE TITLE
Don't set wallpaper if fetching wasn't successful

### ISSUE THREAD

**Issue by Teonyr** [ifl0w/RandomWallpaperGnome3#104] opened 2021-05-19 14:52 UTC
Sometimes fetching doesn't work correctly, which results in a 0 bytes file, which in turn results in a (incorrectly set) blue background image.

Would be nice, if the extension checks for a valid image, before setting it.

I'm using Ubuntu 21.04 with gnome40.

If you need more information, please feel free to ask.

**Comment by ifl0w** [comment] 2021-05-30 20:11
Hello and thanks for the bug report! I did not observe the bug yet, but I'd suspect that the error handling ![here](https://github.com/ifl0w/RandomWallpaperGnome3/blob/2fac0b0bd83ee01a5352a3bec4a806136e5b8f8d/randomwallpaper%40iflow.space/wallpaperController.js#L145) is not optimal. For example, errors occurring while closing the file are not recognized.

Can you give more information on how to reproduce the bug? Which source are you using? Do you know a way to produce the bug reliably?

**Comment by Teonyr** [comment] 2021-06-30 12:15
Hey, sorry for the delay.

My source was reddit with this sr's: wallpaper,wallpapers,ultrahdwallpapers.

Unfortunately (or fortunately?) I wasn't able to reproduce the issue since. 

I did some investigation on my end and it seemed to occur because of name resolution errors.
In the past sometimes I ran into name resolution errors, which prevented websites (or services) from loading. because this was a huge annoyance, I reset my router and changed my network a bit and this fixed the issue.

So I would guess/say, that the issue occurs, if a connection to reddit was successful but later on, the connection to the image itself, wasn't.

**Comment by ifl0w** [comment] 2021-07-14 16:24
Thanks for the update! I'll look into it, to see if I can make this more robust, but it is probably a rare issue. :)

**Comment by neversun** [comment] 2021-09-03 09:23
It happens to me too, but also related to some network issues. I have an access-point started when I turn on my system and the device takes some time before it is actually working (no name resolution is working at this point, no website/browser too). 

But I cannot reproduce it, once the system is running.

**Comment by ifl0w** [comment] 2021-12-15 13:37
This should be solved now. Will be reopened, if anyone still encounters this problem.

**Closed** 2021-12-15 13:36 UTC
